### ISSUE TITLE
General - Common Police Equipment

### ISSUE THREAD

**Issue by itbeginshere** [VanillaGorillas/paranomal-game#10]
Your task is to research what is generally regarded as the industry standard for police equipment.  This would include the following:

- [x] Weapons
- [x] Armour
- [x] Ammo
- [x] Optics 
- [x] Any other gear not mentioned 

In addition to this, also keep track of anything that could be considered an upgrade in the categories mentioned above.

**Comment by Synx-x** [comment]
it done
